version: '3.9'

services:

  ubuntu-server:
    container_name: deployment-server
    build:
      context: '.'
    ports:
      - "2222:22"
    networks:
      - deployment-network
    volumes:
      - ./server:/test


  mysql-db:
    image: mariadb:10.3
    container_name: deployment-mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql_db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'timperia'
      #      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'timperia'
    networks:
      - deployment-network

  postgres-db:
    image: postgres:14
    restart: always
    container_name: deployment-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: timperia
    #      POSTGRES_DB: your-database
    volumes:
      - postgres_db:/var/lib/postgresql/data
    networks:
      - deployment-network

networks:
  deployment-network:
    driver: bridge

volumes:
  postgres_db:
    driver: local
  mysql_db:
    driver: local
